AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Grocery Shopping Lambda Functions

Resources:
  GroceryShoppingShopFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: frisco.schedule
      Runtime: python3.12
      Timeout: 900
      MemorySize: 256
      FunctionName: grocery-shopping-schedule
      ReservedConcurrentExecutions: 1
  
  GroceryShoppingScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: frisco.shop
      Runtime: python3.12
      Timeout: 900
      MemorySize: 256
      FunctionName: grocery-shopping-shop
      ReservedConcurrentExecutions: 1
